version: '3'

services:

    # mqtt broker
    mosquitto:
        build: mosquitto
        restart: always
        network_mode: host
        ports:
            - "1883:1883"
            - "9001:9001"

    # zigbee to mqtt bridge
    zigbee2mqtt:
        container_name: zigbee2mqtt
        depends_on: [mosquitto]
        network_mode: host
        image: koenkk/zigbee2mqtt:latest-dev
        volumes:
            - /zigbee2mqtt/zigbee2udp/configuration:/app/data
            - /run/udev:/run/udev:ro
        devices:
            - /dev/ttyACM0:/dev/ttyACM0
        restart: always
        privileged: true
        environment:
            - TZ=Europe/Prague

    # mqtt to udp bridge
    mqtt2udp:
        depends_on: [mosquitto]
        network_mode: host
        build: mqtt2udp
        restart: always

